version: "2"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    ports:
      - "3000:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    build:
      context: .
      dockerfile: ./docker/mongo.dockerfile
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
