version: "2"
services:
  app:
    networks:
      - backend
    container_name: edge
    restart: always
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    ports:
      - "1995:8000"
    links:
      - mongo
  mongo:
    networks:
      - backend
    container_name: edge_db
    build:
      context: .
      dockerfile: ./docker/mongo.dockerfile
    volumes:
      - ./data:/data/db
    ports:
      - "1996:27017"
networks:
  backend:
    driver: bridge
